ASFLAGS_ADDITIONAL = -c -g -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10819 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -DARDUINO_NUM_SERIAL_PORTS=4
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = /Users/daixingze/Documents/MATLAB/SupportPackages/R2022a/toolbox/target/supportpackages/arduinotarget/registry/..
STACK_SIZE = 64
